document.writeln("<style>");
document.writeln("                .download66{");
document.writeln("                    position: fixed;");
document.writeln("                    width: 70px;");
document.writeln("                    right: 0px;");
document.writeln("                    height: 50px;");
document.writeln("                    bottom: 60px;");
document.writeln("                    z-index: 999;");
document.writeln("                    text-align: center;");
document.writeln("                }");
document.writeln("                .download66 p {");
document.writeln("                    font-size: 1rem;");
document.writeln("                    font-weight: 700;");
document.writeln("                    color: #fff;");
document.writeln("                    line-height: 44px;");
document.writeln("                }");
document.writeln("                ");
document.writeln("                .download66 .btn {");
document.writeln("                    height: 50px;");
document.writeln("                    width: 50px;");
document.writeln("                    line-height: 25px;");
document.writeln("                    text-align: right;");
document.writeln("                    background-color: #ec0909;");
document.writeln("                    position: absolute;");
document.writeln("                    right: 0px;");
document.writeln("                    font-size: 16px;");
document.writeln("                    border: none;");
document.writeln("                    color: #fff;");
document.writeln("                    border-radius: 25px 0 0 25px;");
document.writeln("                    padding-right: 8px;");
document.writeln("                    box-shadow: -1px 3px 1px #c81616;");
document.writeln("                    border: 1px solid #fff;");
document.writeln("                }");
document.writeln("                .download66 i.close {");
document.writeln("                    display: block;");
document.writeln("                    height: 14px;");
document.writeln("                    width: 14px;");
document.writeln("                    float: left;");
document.writeln("                    background-image: url(gb.png);");
document.writeln("                    background-size: 100%;");
document.writeln("                }");
document.writeln("            </style>");
document.writeln("			<div id=\'guanbia\' class=\'download66\'>");
document.writeln("            	<a target=\'\' href=\'https://ye-5.za.ixia.byzicons.com:8443/0149dh/\' class=\'btn\' id=\'apas\'>下载<br>APP</a>");
document.writeln("            </div>");
document.writeln("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js\"></script>");
document.writeln("<style>");
document.writeln("    #share {");
document.writeln("        width: 40px;");
document.writeln("        height: 40px;");
document.writeln("        line-height: 40px;");
document.writeln("        text-align: center;");
document.writeln("        color: #fff;");
document.writeln("        font-size: 14px;");
document.writeln("        border-radius: 40px;");
document.writeln("        box-sizing: unset;");
document.writeln("        border: solid 4px rgba(255,255,255,.8);");
document.writeln("        background: rgba(255,0,0,8);");
document.writeln("        position: fixed;");
document.writeln("        right: 10px;");
document.writeln("        bottom: 140px;");
document.writeln("        z-index: 1;");
document.writeln("        cursor: pointer;");
document.writeln("    }");
document.writeln("    #modal {");
document.writeln("        font-family: Arial, sans-serif;");
document.writeln("        display: none; z-index: 99999999;");
document.writeln("        position: fixed;");
document.writeln("        top: 0;");
document.writeln("        left: 0;");
document.writeln("        width: 100%;");
document.writeln("        height: 100%;");
document.writeln("        background-color: rgba(0,0,0,0.5);");
document.writeln("        align-items: center;");
document.writeln("        justify-content: center;");
document.writeln("    }");
document.writeln("    #modal .container {");
document.writeln("        width: 80%; max-width: 400px;");
document.writeln("        background-color: #fff;");
document.writeln("        border-radius: 5px;");
document.writeln("        padding: 20px;");
document.writeln("        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);");
document.writeln("    }");
document.writeln("    #modal .header2 {");
document.writeln("        background: linear-gradient(90deg, #00cc99, #08c595);");
document.writeln("        padding: 10px;");
document.writeln("        border-radius: 5px;");
document.writeln("        color: white;");
document.writeln("        font-size: 24px; font-weight: bold;");
document.writeln("        text-align: center;");
document.writeln("        margin-bottom: 5px;");
document.writeln("    }");
document.writeln("    #modal .message {");
document.writeln("        font-size: 21px;");
document.writeln("        text-align: center;");
document.writeln("        margin-bottom: 10px; margin-top: 15px;");
document.writeln("    }");
document.writeln("    #modal .button {");
document.writeln("        padding: 10px 10px;");
document.writeln("        border-radius: 5px;");
document.writeln("        border: none;");
document.writeln("        font-size: 18px;");
document.writeln("        cursor: pointer;");
document.writeln("        width: 100%;");
document.writeln("        margin: 5px auto;");
document.writeln("    }");
document.writeln("    #modal .blue-button {");
document.writeln("        background-color: #0bab33;");
document.writeln("        color: white;");
document.writeln("    }");
document.writeln("    #modal .gray-button {");
document.writeln("        background-color: #95a5a6;");
document.writeln("        color: white;");
document.writeln("    }");
document.writeln("    #modal #countdown span {");
document.writeln("        color: red;");
document.writeln("    }");
document.writeln("    #countdown {");
document.writeln("        text-align: center;");
document.writeln("    }");
document.writeln("     #countdown2 {");
document.writeln("        text-align: center;");
document.writeln("        color: red; font-size: 19px;");
document.writeln("    }");
document.writeln("     #modal .link {");
document.writeln("        font-size: 1px; height: 1px; color: #fff;");
document.writeln("        text-align: center;");
document.writeln("        border: 1px solid #e0e0e0;");
document.writeln("        word-wrap: break-word;");
document.writeln("    }");
document.writeln("");
document.writeln("    #qrcode {");
document.writeln("        display: flex;");
document.writeln("        justify-content: center;");
document.writeln("        align-items: center;");
document.writeln("        margin-top: 15px;");
document.writeln("         margin-bottom: 15px;");
document.writeln("    }");
document.writeln("");
document.writeln("    #qrcode img {");
document.writeln("        margin: auto;");
document.writeln("    }");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div style=\'width:100%;max-width:720px;position: fixed;bottom: 0px;left: 0px;right: 0;margin: 0 auto;z-index: 999;\'>");
document.writeln("    <div class=\'dbfont1\' onclick=\'kaifenx();\' style=\'height: 40px; background-color:rgba(0,0,0,.7);width: 100%;border-top: 1px solid #fff;text-align: center;font-weight:700;color:#fff;line-height: 40px;\'>");
document.writeln("        <span onclick=\"showModal()\" style=\'color:#fff;font-weight:bold;padding:5px 2px;font-size: 20px;\' class=\'smtm\'>&#36523;&#36793;&#20154;&#25171;&#19981;&#24320;&#26412;&#31449;&#24590;&#20040;&#21150;&#65311;&#35831;<span style=\'background-color: #ec0909;border-radius: 5px;color: #fff;margin-left: 6px;padding: 4px 4px;\'>&#28857;&#20987;&#20998;&#20139;</span></span>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<div id=\"modal\">");
document.writeln("    <div class=\"container\">");
document.writeln("        <div class=\"header2\">链接分享</div>");
document.writeln("        <div class=\"message\">链接已复制，请发送给好友！</div>");
document.writeln("        <div class=\"link\" id=\"shareLink\">0149</div>");
document.writeln("        <div id=\"qrcode\"></div>");
document.writeln("         <div id=\"countdown2\">或面对面分享，使用浏览器扫码</div>");
document.writeln("        <div id=\"countdown\">弹窗将在 <span>20</span> 秒后自动关闭</div>");
document.writeln("        <div>");
document.writeln("            <button class=\"button blue-button\" onclick=\"openApp(\'weixin://\')\">打开微信</button>");
document.writeln("            <button class=\"button\" onclick=\"closeModal()\">立即关闭</button>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<script>");
document.writeln("function showModal() {");
document.writeln("    let currentPageURL = window.location.href;");
document.writeln("    let formattedText =`");
document.writeln("    ${currentPageURL}#FX`;");
document.writeln("    document.getElementById(\'shareLink\').innerText = formattedText;");
document.writeln("    document.getElementById(\'modal\').style.display = \'flex\';");
document.writeln("");
document.writeln("    copyToClipboard(formattedText);");
document.writeln("");
document.writeln("    document.getElementById(\'qrcode\').innerHTML = \"\";");
document.writeln("    new QRCode(document.getElementById(\"qrcode\"), {");
document.writeln("        text: currentPageURL,");
document.writeln("        width: 150,");
document.writeln("        height: 150,");
document.writeln("        colorDark: \"#000000\",");
document.writeln("        colorLight: \"#ffffff\",");
document.writeln("        correctLevel: QRCode.CorrectLevel.H");
document.writeln("    });");
document.writeln("");
document.writeln("    let countdown = 20;");
document.writeln("    let countdownInterval = setInterval(() => {");
document.writeln("        countdown--;");
document.writeln("        document.querySelector(\'#countdown span\').innerText = countdown;");
document.writeln("");
document.writeln("        if (countdown === 0) {");
document.writeln("            closeModal();");
document.writeln("            clearInterval(countdownInterval);");
document.writeln("        }");
document.writeln("    }, 1000);");
document.writeln("}");
document.writeln("");
document.writeln("function copyToClipboard(text) {");
document.writeln("    const el = document.createElement(\'textarea\');");
document.writeln("    el.value = text;");
document.writeln("    document.body.appendChild(el);");
document.writeln("    el.select();");
document.writeln("    document.execCommand(\'copy\');");
document.writeln("    document.body.removeChild(el);");
document.writeln("    alert(\'内容已成功复制到剪贴板！\');");
document.writeln("}");
document.writeln("");
document.writeln("function closeModal() {");
document.writeln("    document.getElementById(\'modal\').style.display = \'none\';");
document.writeln("}");
document.writeln("");
document.writeln("function openApp(url) {");
document.writeln("    window.open(url, \'_blank\');");
document.writeln("}");
document.writeln("");
document.writeln("    function closeBanner() {");
document.writeln("        // 隐藏包含横幅的最外层div");
document.writeln("        document.querySelector(\'div[style*=\"max-width:720px\"]\').style.display = \'none\';");
document.writeln("    }");
document.writeln("");
document.writeln("    function kaifenx() {");
document.writeln("        // 您的kaifenx函数的代码");
document.writeln("        console.log(\'执行kaifenx函数\');");
document.writeln("    }");
document.writeln("</script>");